INSERT INTO [dbo].[Feed] ([Feed_id], [Feed_name], [Caloric], [Kind], [Purpose], [Cost], [Discount]) VALUES (1, N'Віскас', 362, N'М`ясоїд', N'Кіт', 24, 0)
INSERT INTO [dbo].[Feed] ([Feed_id], [Feed_name], [Caloric], [Kind], [Purpose], [Cost], [Discount]) VALUES (2, N'МУЛЬТИ-ВІТАМІН', 78, N'Травоїд', N'Хомяк', 456, 0)
INSERT INTO [dbo].[Feed] ([Feed_id], [Feed_name], [Caloric], [Kind], [Purpose], [Cost], [Discount]) VALUES (7, N'Фріскас', 312, N'М`ясоїд', N'Кіт', 56, 0)
INSERT INTO [dbo].[Feed] ([Feed_id], [Feed_name], [Caloric], [Kind], [Purpose], [Cost], [Discount]) VALUES (8, N'ЗОЛОТЕ-ЖИТО', 98, N'Травоїд', N'Хомяк', 1234, 0)
INSERT INTO [dbo].[Feed] ([Feed_id], [Feed_name], [Caloric], [Kind], [Purpose], [Cost], [Discount]) VALUES (9, N'АЛЬФА', 179, N'М''ясо', N'Єнот', 89, 5)
